deployments:
  application:  # name of the application
    # image
    image: nginx
    tag: 1.14.2
    port: 80 # this is the port that the application uses

    env: 
      key: value

    storage:
      main: # name the storage, Nothing can have the same name in the namespace
        class: longhorn # only been tested with longhorn
        path: /data #Path in the container
        capacity: 1G

    ingress: 
      url: nginx.your_url.com
      cert_env: staging #staging or production

secrets:
  []
