{{- range $key, $value := .Values.deployments }}
{{- if and (eq $value.type "deployment") $value.clusterRbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-cluster-role" ($value.serviceAccount.name | default $key) | quote }}
rules:
  {{- toYaml $value.clusterRbac.rules | nindent 2 }}
---
{{- end }}
{{- end }}
