{{- $namespace := .Release.Namespace -}}
{{- range $key, $value := .Values.deployments }}
{{- if eq $value.type "daemonset"}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $key | quote}}
  namespace: {{ $namespace }}
  labels:
    app: {{ $key | quote}}
spec:
  selector:
    matchLabels:
      app: {{ $key | quote }}
  template:
    metadata:
      labels:
        app: {{ $key | quote }}
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: {{ $key | quote }}
        image: {{ $value.image}}:{{ $value.tag}}
        ports:
        - containerPort: {{ $value.port }}
        {{- if $value.env}}
        env:
          {{- range $env_key, $env_value := $value.env}}
          - name: {{ $env_key }}
            value: {{ $env_value }}
          {{- end}}
        {{- end}}
        {{- if or $value.storage $value.files }}
        volumeMounts:
          {{- if $value.storage }}
          {{- range $storageName, $storage := $value.storage }}
          - name: {{ $storageName }}
            mountPath: {{ $storage.path }}
            {{- if and (eq ($storage.type | default "pvc") "hostPath") $storage.readOnly }}
            readOnly: {{ $storage.readOnly }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- if $value.files }}
          {{- range $file := $value.files }}
          - name: {{ $file.configName }}
            mountPath: {{ $file.mountPath }}
          {{- end }}
          {{- end }}
        {{- end }}

      {{- if or $value.storage $value.files }}
      volumes:
        {{- if $value.storage }}
        {{- range $storageName, $storage := $value.storage }}
        {{- $volumeType := $storage.type | default "pvc" }}
        - name: {{ $storageName }}
          {{- if eq $volumeType "hostPath" }}
          hostPath:
            path: {{ $storage.hostPath }}
            {{- if $storage.hostPathType }}
            type: {{ $storage.hostPathType }}
            {{- end }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ $storageName }}-pvc
          {{- end }}
        {{- end }}
        {{- end }}
        {{- if $value.files }}
        {{- range $file := $value.files }}
        - name: {{ $file.configName }}
          configMap:
            name: {{ $file.configName }}
        {{- end }}
        {{- end }}
      {{- end }}
---
{{- end }}
{{- end}}
