{{- $namespace := .Release.Namespace -}}
{{- range $key, $value := .Values.deployments }}
  {{- if eq $value.type "deployment"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key | quote }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $key | quote }}
spec:
  replicas: {{ $value.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $key | quote }}
  template:
    metadata:
      labels:
        app: {{ $key | quote }}
    spec:

    {{- if $value.serviceAccount.create }}
      serviceAccountName: {{ $value.serviceAccount.name | default $key | quote }}
    {{- end }}
      containers:
      - name: {{ $key | quote }}
        image: {{ $value.image }}:{{ $value.tag }}

        ports:
    {{- if $value.port }}
        - containerPort: {{ $value.port }}
    {{- end }}

    {{- if $value.portMap }}
      {{- range $portKey, $port := $value.portMap }}
        - containerPort: {{ $port.internal }}
          name: {{ $portKey }}
      {{- end }}
    {{- end }}


    {{- if $value.args }}
        args: {{ toJson $value.args }}
    {{- end }}

    {{- if $value.env }}
        resources:
          requests:
            cpu: {{ $value.requests.cpu | default "100m" | quote }}
            memory: {{ $value.requests.memory | default "100Mi" | quote }}
          limits:
            cpu: {{ $value.limits.cpu | default "100m" | quote }}
            memory: {{ $value.limits.memory | default "100Mi" | quote }}

      {{- if eq $value.priverlaged "true" }}
        securityContext:
          privileged: true
      {{- end }}

        env:
      {{- range $env_key, $env_value := $value.env }}
          - name: {{ $env_key }}
            value: {{ $env_value | quote }}
      {{- end }}
      {{- range $env_key, $env_value := $value.secretEnv }}
          - name: {{ $env_key }}
            valueFrom:
              secretKeyRef:
                name: {{ $env_value.name }}
                key: {{ $env_value.key }}
      {{- end }}
    {{- end }}

    {{- if or $value.storage $value.files }}
        volumeMounts:
      {{- if $value.storage }}
        {{- range $storageName, $storage := $value.storage }}
          - name: {{ $storageName }}
            mountPath: {{ $storage.path }}
          {{- if and (eq ($storage.type | default "pvc") "hostPath") $storage.readOnly }}
            readOnly: {{ $storage.readOnly }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if $value.files }}
        {{- range $file := $value.files }}
          - name: {{ $file.configName }}
            mountPath: {{ $file.mountPath }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- if or $value.storage $value.files }}
      volumes:
      {{- if $value.storage }}
        {{- range $storageName, $storage := $value.storage }}
        {{- $volumeType := $storage.type | default "pvc" }}
        - name: {{ $storageName }}
          {{- if eq $volumeType "hostPath" }}
          hostPath:
            path: {{ $storage.hostPath }}
            {{- if $storage.hostPathType }}
            type: {{ $storage.hostPathType }}
            {{- end }}
          {{- end }}
          {{- if eq $volumeType "empty" }}
          emptyDir:
            {{- if $storage.capacity }}
            sizeLimit: {{ $storage.capacity }}
            {{- end }}
          {{- end }}
          {{- if eq $volumeType "pvc" }}
          persistentVolumeClaim:
            claimName: {{ $storageName }}-pvc
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if $value.files }}
        {{- range $file := $value.files }}
        - name: {{ $file.configName }}
          configMap:
            name: {{ $file.configName }}
        {{- end }}
      {{- end }}
    {{- end }}

  {{- end }}
---
{{- end }}