{{- $namespace := .Release.Namespace -}}
{{- range $key, $value := .Values.deployments }}
  {{- if eq $value.type "deployment"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key | quote }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $key | quote }}
spec:
  replicas: {{ $value.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $key | quote }}
  template:
    metadata:
      labels:
        app: {{ $key | quote }}
    spec:

    {{- if $value.serviceAccount }}
      serviceAccountName: {{ $value.serviceAccount.name | default $key | quote }}
    {{- end }}

    {{- if $value.master }}
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
    {{- end }}

      containers:
      - name: {{ $key | quote }}
        image: {{ $value.image }}:{{ $value.tag }}

        ports:
{{ include "ports.entries" $value | indent 8 }}

    {{- if $value.args }}
{{ include "config.args" $value | indent 8 }}
    {{- end }}

    {{- if $value.env }}
{{ include "resources.spec" $value | indent 8 }}

      {{- if eq $value.priverlaged "true" }}
{{ include "config.security" $value | indent 8 }}
      {{- end }}

        env:
{{ include "env.vars" $value | indent 10 }}
    {{- end }}

    {{- if or $value.storage $value.files }}
        volumeMounts:
{{ include "storage.volumeMounts" $value | indent 10 }}
    {{- end }}

    {{- if or $value.storage $value.files }}
      volumes:
{{ include "storage.volumes" $value | indent 8 }}
    {{- end }}

  {{- end }}
---
{{- end }}
