{{- $namespace := .Release.Namespace -}}
{{- range $key, $value := .Values.deployments }}
{{- range $storageName, $storage := $value.storage }}
{{- if $storage.class }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $storageName }}-pvc
  namespace: {{ $namespace }}
spec:
  storageClassName: {{ $storage.class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $storage.capacity }}
---
{{- end }}
{{- end }}
{{- end }}
