{{- $namespace := .Release.Namespace -}}
{{- range $key, $value := .Values.deployments }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  namespace: {{ $namespace }}
spec:
  selector:
    app: {{ $key | quote }}
  ports:
    {{- if $value.port }}
    - protocol: TCP
      port:  80
      targetPort: {{ $value.port }}
    {{- end }}
    {{- if $value.portMap }}
    {{- range $portsKey, $ports := $value.portMap }}
    - name: {{ $portsKey }}
      protocol: {{ $ports.protocol | default "TCP" }}
      port:  {{ $ports.external }}
      targetPort: {{ $ports.internal }}
    {{- end }}
    {{- end }}
---
{{- end}}
