{{- $namespace := .Release.Namespace -}}
{{- range $key, $value := .Values.deployments }}
{{- if $value.roles }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $key }}
  namespace: {{ $namespace }}
{{- end }}
{{- end }}
